---
- name: Install apache2
  apt:
    name:
      - apache2
    state: present
    update_cache: yes

- name: Copy new html to root directory
  template:
    src: index.html
    dest: /var/www/html


